version: 2

updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "⬆️"
    groups:
      aspnetcore:
        patterns:
          - "Microsoft.AspNetCore*"
      swashbuckle:
        patterns:
          - "Swashbuckle*"
      tunit:
        patterns:
          - "TUnit*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "⬆️"
    groups:
      actions:
        patterns:
          - "*"
