<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../../src/Chorn.AspNetCore.ProblemDetails/Chorn.AspNetCore.ProblemDetails.csproj" />
	</ItemGroup>

</Project>
