<Project>
	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

	<PropertyGroup>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageProjectUrl>https://github.com/ChristophHornung/problemdetails</PackageProjectUrl>
		<RepositoryUrl>https://github.com/ChristophHornung/problemdetails</RepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<None Include="$(MSBuildThisFileDirectory)../README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>
